version: '3.8'
services:
de  postgres:
    image: timescale/timescaledb:latest-pg15  
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo_pass
      POSTGRES_DB: echoagents
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
